package refname

import (
	"strings"
	"testing"
)

func TestValidate(t *testing.T) {
	cases := []struct {
		name      string
		ref       string
		wantError bool
		wantMsg   string
	}{
		{name: "normal branch", ref: "feature/add-login", wantError: false},
		{name: "planning branch generated by service", ref: "planning/task-001-abc123", wantError: false},
		{name: "empty", ref: "", wantError: true, wantMsg: "empty"},
		{name: "leading dash (flag injection)", ref: "--force", wantError: true, wantMsg: "must not start"},
		{name: "contains ..", ref: "feature/..escape", wantError: true, wantMsg: "'..'"},
		{name: "trailing slash", ref: "feature/", wantError: true, wantMsg: "forbidden suffix"},
		{name: ".lock suffix", ref: "feature.lock", wantError: true, wantMsg: "forbidden suffix"},
		{name: "contains @{ (reflog)", ref: "feature@{0}", wantError: true, wantMsg: "'@{'"},
		{name: "contains tilde", ref: "feature~1", wantError: true, wantMsg: "forbidden character"},
		{name: "contains colon", ref: "feature:bad", wantError: true, wantMsg: "forbidden character"},
		{name: "contains question mark", ref: "feature?", wantError: true, wantMsg: "forbidden character"},
		{name: "contains space", ref: "feature bad", wantError: true, wantMsg: "whitespace"},
		{name: "contains newline", ref: "feature\nbad", wantError: true, wantMsg: "control"},
		{name: "contains backslash", ref: "feature\\bad", wantError: true, wantMsg: "forbidden character"},
		{name: "contains caret", ref: "feature^bad", wantError: true, wantMsg: "forbidden character"},
		{name: "contains asterisk", ref: "feature*", wantError: true, wantMsg: "forbidden character"},
		{name: "contains open bracket", ref: "feature[bad", wantError: true, wantMsg: "forbidden character"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := Validate(tc.ref)
			if tc.wantError {
				if err == nil {
					t.Fatalf("expected error, got nil")
				}
				if tc.wantMsg != "" && !strings.Contains(err.Error(), tc.wantMsg) {
					t.Fatalf("error %q should mention %q", err.Error(), tc.wantMsg)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
		})
	}
}
